### ISSUE TITLE
[REQUEST] Add inbuilt dotenv-expand functionality

### ISSUE THREAD

**Issue by saxoncameron** [ovos/dotenv-flow-cli#2]
The [dotenv-cli](https://github.com/entropitor/dotenv-cli) package comes with inbuilt [dotenv-expand](https://github.com/motdotla/dotenv-expand) functionality.

This is appropriate to add to `dotenv-flow-cli` instead of `dotenv-flow`, because `dotenv-expand` can be used alongside `dotenv-flow` already, like so:
```js
const dotenv = require('dotenv-flow');
const dotenvExpand = require('dotenv-expand');

dotenvExpand(dotenv.config());
```
However, `dotenv-expand` doesn't have inherent CLI support - which is why `dotenv-cli` has it built in.
It's for this reason that `dotenv` doesn't include `dotenv-expand` out of the box as well, since they can be used separately/together.

In the interim, I'm getting around this by using `dotenv-cli` and pointing it manually to my `.env.local` file like this:
```js
dotenv -e .env.local <my commands>
```
It would be nicer/simpler to use `dotenv-flow-cli` if it supported variable expansion :)

**Comment by yovanoc** [comment]
Agree with that but dead project..
